apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sftp.name }}-secret
  labels:
    app: {{ .Values.sftp.name }}
type: Opaque
data:
  username: {{ .Values.sftp.credentials.username | b64enc | quote }}
  password: {{ .Values.sftp.credentials.password | b64enc | quote }}
