apiVersion: v1
kind: Secret
metadata:
  name: app-env-secret
  labels:
    {{- include "order-system.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.app.env.secretKey | quote }}
  DATABASE_USER: {{ .Values.mysql.auth.username | quote }}
  DATABASE_PASSWORD: {{ .Values.mysql.auth.password | quote }}
  DATABASE_NAME: {{ .Values.mysql.auth.database | quote }}
  DATABASE_HOST: {{ .Values.mysql.name | quote }}
  DATABASE_PORT: {{ .Values.mysql.service.port | quote }}
