{{- if and .Values.mysql.enabled .Values.mysql.initdb.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-scripts
  labels:
    {{- include "order-system.mysql.labels" . | nindent 4 }}
data:
  init-schema.sql: |
{{ .Files.Get "files/database_schema.sql" | indent 4 }}
{{- end }}
