{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  labels:
    {{- include "order-system.mysql.labels" . | nindent 4 }}
type: Opaque
stringData:
  ROOT_PASSWORD: {{ .Values.mysql.auth.rootPassword | quote }}
  DATABASE: {{ .Values.mysql.auth.database | quote }}
  USER: {{ .Values.mysql.auth.username | quote }}
  PASSWORD: {{ .Values.mysql.auth.password | quote }}
{{- end }}
