{{- if .Values.mysql.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.mysql.name }}
  labels:
    {{- include "order-system.mysql.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.mysql.name }}
  serviceName: {{ .Values.mysql.name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.name }}
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.mysql.service.port }}
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: PASSWORD
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            {{- if .Values.mysql.initdb.enabled }}
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d/
            {{- end }}
          {{- with .Values.resources.mysql }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- if .Values.mysql.initdb.enabled }}
        - name: init-scripts
          configMap:
            name: mysql-init-scripts
        {{- end }}
  {{- if .Values.mysql.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.mysql.persistence.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.mysql.persistence.size }}
  {{- end }}
{{- end }}
