apiVersion: v2
name: order-system
description: A Helm chart for Order Management System with MySQL database
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - order-management
  - fastapi
  - mysql
maintainers:
  - name: Kevin
